---
- name: Print reports about drive mounts
  hosts: "{{ target }}"
  gather_facts: true
  vars_files:
    - vars/report_vars.yml
  tasks:
    - name: parse through mount variable
      ansible.builtin.debug: 
        msg: |
            "Drive is mounted at {{ item.mount }} 
            {% if item.block_used/item.block_total * 100 > 80 -%} 
            ----- drive is UNHEALTHY!!: {{ item.block_used/item.block_total * 100 }}% full. 
            {% elif item.block_used/item.block_total * 100 < 80 -%} 
            ----- drive is HEALTHY: {{ item.block_used/item.block_total * 100 }}%
            {%endif %}"
      loop: "{{ ansible_mounts }}"
      loop_control:
        label: "{{  item.mount }}"
      register: disk_var

    - name: copy results to a hw info report
      ansible.builtin.template: 
        src: templates/disk-report.txt.j2
        dest: "{{ item.dest }}"
        force: True
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ copy_results }}"
      register: copy_handoff
      notify: display new file

  handlers:
    - name: display new file
      ansible.builtin.debug:
        msg: |
          "{{ lookup('pipe','cat') + item.dest | quote }}"
      loop: "{{ copy_results }}"
